language: node_js
node_js:
- node
notifications:
  slack:
    rooms:
      secure: YCpkuzmBvzR9acTO/PfJN4025pIXu2juq/8NAgLwa3h8mubOu7qkKXnk1vq2LCYV2AQZLKyS7/e7UnFDvH061MSSKZT/Au0G2juvPwbqqUTMBVQOhZQH59FfJFy0f2PHUCeLZiqBwEHSOyn3NwsNDC06nMcODKiLMTTlrl5Q3UG+SdY3WMrus2d0XDBs96GWzHxPcNnCE9erUk0vgF6eshS7/+jXIIqyZioYLsuFgDVPoytRom2OjWJp5G0SYFO2V/sVOi0qdvS9r65c74fLI9kVoMxaBV56dRVNmNQpGox2+Hh/bZcwA4DUqdaV8CFJZvcPJVi582K6ZGrvBjAq1ed3QTrH+F0QAmgxCwyTrDTd/idiiJBGt9co3EyJ2fuqKJi5sqSyU5VAO3rSmgKTVxxuEdirGiI9iVJv3rcITBCNBXIgqhuNncItn/V8ANGMAfoRIVsV4oJ1LAKgrG8HEsy8o9bZ92QlXB44t4CChVDhWnauVmxlxoqnE5K0HMtH2ecLv2PghAKJROoC5rFWqEimeE8ykiJvgDHVv/S76vYPcY3FfbURn1DcDc/09vJrspkFBT4f7ECoMvRIX601AaE9q21VaQOMUfrYR4QpQkNoy3GDfI9Cl9wePJWo1boQtEn6g8F6wqXnUMl8Y/Uez7lUp93wIxYrFT9oCiQjD0U=
