language: node_js
node_js:
- node
notifications:
  slack:
    secure: R0m217h4QRFXQQ/l5IurNNMl1a5Rr+DvFTHP4Xg+fdwyI2031WTxm9wMyIlZK7a2lR1+Tnjccwyg4YgBKCkCfCD6M8WvOTqi+yid3m5QmmQ5/2cRZu2CJgfW6xliscX+JLlkYUwcsW4KPWh44hVLK4RHTFtFBGJgPPJvIm6bNKz5UCKL2z9gsEHQR6xwDiIrLNDj392T5KT3vfAasRQerFhYA7RwtL7lbpTvdoMqxPZPTBxi8FLA1CCrLJGAV9Ys7NkBPvtkH0yAdAQToPZ+QlPBYwFSfz27l2EU+zOtKWHMOu76bt2hpsU+U1bjzNf9Q3STAw82BtnsgtEA+dRN+1wk49AQvv8tAeHmA95KyoE/hmeDlhqDNg78codFZiava6j/dm4es3J9z8aoYPG4El3F6bJlRM7pvNMU5CrwCaMJhnsJzH1IUvCA413JUb3JUj2b8suAE1CsOjxCpxARLs81o6cP51PTtyWjN0Jt+yzmWpFRAIVFflS2VMna3GIY+2YGI6wlFkuR2tzIXe52Jf1nzEXrkscAHXBHloEX5zZNutnZeDRE318GsYQmRul/p84PU23bJL9ia3qHHgtnSx22pQJun93QsOP6Fm2HytnETTsod/Bt4rjvOQmUME3sSqA64IyCGtNk3LlHE+1jKvQyITwbMloKnW9PZp17700=
