language: node_js
node_js:
 - "node"
 notifications:
  slack:
    rooms:
      secure:
RXspS47s4E2SW267N2zESlxwP1TjV6ipF7HTy2vMEbc+G8bJ0OMxXpDYSUOgVUXRGzCdFPtK7J4dr3ddWstN6xcGyn3FX0JZ5YDL0AXuY9e0pNSZXZlfTuenSUug/+oLaYh/kyMbOErnGrm0mp4ouV4/bAEAUYrsSs1cDxCJWU9UYa5JWrOXPEhbQf+rjt5enRXLDTYUv8+kqrR4Zl/RAHopZmG+8QyOJkMtnWGoyKO5EilOocKCElQyWhCgLK06R/SmLk3BjmMGT24ZsdIdZ3Njc0ar2leKrOHx5OpJnzzA/4TP3YJmpOxVt1EAiT1bznK6BLaFQmrhFbqo/lJwYovQBNXbWJe1SCsBWMkCjJm+iKNc0G5rBaepoERRgSQD/3Ll7gL6RWsjx7i5yNx64JJlzFIkbit3hUFIard2MxW0hbtKwfAj772qTSlePUXSpQZ2rk9Or4A7aC2ESp91E8m+WwAFE1cP6nQNcKUqYUzImeB7+eRhfU/uyQwsDUdd15wNq5ubbO7qnEwZ5a892upxdf0FN1pkEMawK4bUBQNSjxl2f7+90iKNsJiuKYOF/l1bihDdp8O7dYJw4wNeITGAFe8xbk3o20TpJBFDT8ISd64dXY7qI2r+b7SyUwijM9PC/sih8r/d6JSBJf0Hhiz23BIWsWvCz9+lizCLyvo=
